name: dslink_cast
description: Google Cast DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  google_cast:
    git: https://github.com/DirectMyFile/chromecast.dart.git
  upnp:
    git: https://github.com/DirectMyFile/upnp.dart.git
